[pytest]
minversion = 6.0
addopts = -ra -q --asyncio-mode=auto
testpaths =
    app/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Configuration for pytest-cov
[coverage:run]
branch = True
source = app

[coverage:report]
show_missing = True
skip_covered = True
fail_under = 80
